version: 2.1

orbs:
  flutter: circleci/flutter@1.1.0
  codecov: codecov/codecov@3.2.4

executors:
  android:
    docker:
      - image: "cimg/android:2022.06"

commands:
  install-flutter:
    steps:
      - checkout
      - run:
          name: Set Flutter vesion
          command: echo 'export FLUTTER_VERSION="3.3.10"' >> $BASH_ENV
      - flutter/install_sdk_and_pub:
          flutter_version: ${FLUTTER_VERSION}
      - run: flutter pub run build_runner build --delete-conflicting-outputs

  apply_placeholder:
    steps:
      - run:
          name: Apply placeholder
          command: mv lib/config/secrets.dart.example lib/config/secrets.dart

  dart_analyze:
    steps:
      - run:
          name: Check analyze
          command: |
            flutter analyze || exit

  test-flutter:
    steps:
      - run:
          name: Run tests
          command: |
            flutter test --coverage

  build-android:
    description: Builds APK for Android
    steps:
      - run:
          command: flutter build apk --debug
          name: Build APK

  format:
    description: Run checks if Flutter code is formatted
    steps:
      - run:
          command: >-
            flutter format --set-exit-if-changed . || { echo 'Format check
            failed'; exit 1; }
          name: Analyze

jobs:
  setup-and-format:
    executor:
      name: android
    steps:
      - checkout
      - apply_placeholder
      - install-flutter
      - format
      - dart_analyze

  test-coverage:
    executor:
      name: android
    steps:
      - checkout
      - apply_placeholder
      - install-flutter
      - test-flutter
      - codecov/upload

  build-android:
    executor: android
    steps:
      - checkout
      - apply_placeholder
      - install-flutter
      - build-android
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-debug.apk
          destination: app-debug.apk

workflows:
  main:
    jobs:
      - setup-and-format
      - build-android:
          requires:
            - setup-and-format
      - test-coverage:
          requires:
            - setup-and-format
